# Generated by Django 2.2.3 on 2019-07-21 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='ann_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this annotation holds importance for you', validators=[userprofile.models.datevalidator]),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='ann_text',
            field=models.CharField(help_text='The desired story you want to tell to all other users', max_length=250),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=49.2642, help_text='The latitude of the location up to 4 decimal places', max_digits=10),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='location_name',
            field=models.CharField(default='location name', help_text='The name of the location of the annotation', max_length=30),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=123.2532, help_text='The longitude of the location up to 4 decimal places', max_digits=10),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='owner',
            field=models.ForeignKey(help_text='The user this annotation belongs too', on_delete=django.db.models.deletion.CASCADE, related_name='location_user', to='userprofile.Userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bio',
            field=models.CharField(help_text='Let all the users know something interesting about yourself', max_length=180),
        ),
    ]
