# Generated by Django 2.2.3 on 2019-07-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190721_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isdeleted',
            field=models.BooleanField(default=False, help_text='Admin field only'),
        ),
    ]
