# Generated by Django 2.2.3 on 2019-07-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20190723_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='ann_text',
            field=models.CharField(help_text='The desired story you want to tell to all other users', max_length=1200),
        ),
    ]
