# Generated by Django 2.2.3 on 2019-08-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_story_private_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_owner',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='stories',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='community',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
