# Generated by Django 2.2.3 on 2019-08-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20190801_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='story',
            field=models.CharField(blank=True, help_text='The story name for the group of annotations', max_length=50),
        ),
        migrations.AddField(
            model_name='annotation',
            name='story_privacy',
            field=models.BooleanField(default=False, help_text='Is the story visible to everyone or just community members'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='community',
            field=models.CharField(null=True, help_text='What is the community that you represent', max_length=50, unique=True),
        ),
    ]
