# Generated by Django 2.2.3 on 2019-08-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20190801_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='community',
            field=models.CharField(help_text='What is the community that you represent', max_length=50, null=True),
        ),
    ]
