# Generated by Django 2.2.3 on 2019-08-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_auto_20190802_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='community',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='community_blah',
        ),
        migrations.AddField(
            model_name='annotation',
            name='community_annotation',
            field=models.ManyToManyField(blank=True, to='userprofile.Community'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='community_user',
            field=models.ManyToManyField(blank=True, to='userprofile.Community'),
        ),
    ]
