# Generated by Django 2.2.3 on 2019-08-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_auto_20190804_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_privacy',
        ),
    ]
