# Generated by Django 2.2.3 on 2019-08-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_remove_annotation_annotation_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_community',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Community'),
        ),
    ]
