# Generated by Django 2.2.3 on 2019-07-23 22:24

from django.db import migrations, models
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ishome',
            field=models.BooleanField(default=False, help_text='The tag to identify whether the location is a home or not'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groupby',
            field=models.CharField(blank=True, help_text='Categorization field make groups for users', max_length=100),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=49.2642, help_text='The latitude of the location up to 4 decimal places', max_digits=10, validators=[userprofile.validators.latitudevalidator]),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=123.2532, help_text='The longitude of the location up to 4 decimal places', max_digits=10, validators=[userprofile.validators.longitudevalidator]),
        ),
    ]
