# Generated by Django 2.2.3 on 2019-07-25 21:44

from django.db import migrations, models
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190723_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='ann_date_time',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this annotation holds importance for you', validators=[userprofile.validators.datevalidator]),
        ),
    ]
