# Generated by Django 2.2.3 on 2019-07-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20190725_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ann_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
