# Generated by Django 2.2.3 on 2019-07-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_annotation_ann_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='ishome',
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('research', 'Research'), ('school', 'School'), ('attraction', 'Attraction'), ('custom', 'Custom')], help_text='The tag to identify whether the annotation represents any category', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False, help_text='Would you like your profile to be accessible by everyone?'),
        ),
    ]
