# Generated by Django 2.2.3 on 2019-08-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20190801_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_owner',
        ),
    ]
