# Generated by Django 2.2.3 on 2019-08-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20190801_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='stories',
            field=models.ForeignKey(default='', help_text='The annotations that are part of the story', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_owner',
            field=models.ForeignKey(default='', help_text='the owner of the story', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='community',
            field=models.ForeignKey(default='', help_text='The community user belongs too', on_delete=django.db.models.deletion.CASCADE, to='userprofile.Community'),
        ),
    ]
