# Generated by Django 2.2.3 on 2019-08-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_auto_20190801_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='story',
            field=models.CharField(blank=True, help_text='The story name for the group of annotations', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='community',
            field=models.CharField(blank=True, help_text='What is the community that you represent', max_length=50, null=True),
        ),
    ]
