# Generated by Django 2.2.3 on 2019-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_auto_20190802_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='community',
            new_name='community_blah',
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(help_text='The name of the community needs to be unique', max_length=50, null=True, unique=True)),
                ('annotations', models.ManyToManyField(blank=True, to='userprofile.Annotation')),
                ('users', models.ManyToManyField(blank=True, to='userprofile.Userprofile')),
            ],
            options={
                'verbose_name': 'communities',
            },
        ),
    ]
