# Generated by Django 2.2.3 on 2019-08-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_auto_20190803_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.TextField(blank=True, help_text='The tag to identify whether the annotation represents any category'),
        ),
    ]
