# Generated by Django 2.2.3 on 2019-08-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_auto_20190804_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='private',
            new_name='user_privacy',
        ),
    ]
